title: Juf Det
description: De kunstklas van Juf Det in Heeg
url: https://jufdet.nl


defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: ""
      type: posts
    values:
      layout: "post"
  - scope: 
      path: ""
      type: "artworks"
    values:
      layout: "artwork"
      permalink: /kunst/:title

collections:
  artworks:
    output: true