title: Juf Det
description: 
url: 

permalink: /blog/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
